name: tp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.3.4
  image_picker: ^1.0.7
  google_mlkit_face_detection: ^0.9.0
  image: ^4.1.3
  audioplayers: ^5.2.1
  path: ^1.8.3
  provider: ^6.1.1
  logging: ^1.2.0
  camera: ^0.10.5+9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/